services:
  
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password1234
      MYSQL_DATABASE: files
    volumes:
      - db_data:/var/lib/mysql
      # runs ./sql/init.sql only the first time (if db_data is not present)
      # to execute again, delete db_data volume manually
      - ./sql:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    image: node:latest
    working_dir: /app
    container_name: backend
    volumes:
      - ./backend/:/app
      - ./uploads/:/uploads
    environment:
      PORT: 3000
      JWT_SECRET: Secret1234
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password1234
      DB_NAME: files
    depends_on:
      mysql:
        condition: service_healthy
    command: bash -c "npm run dev"
    ports:
      - "3000:3000"
  
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./uploads:/uploads
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data:
